name = "nexum-backend"
main = "src/index.ts"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
