name = "nexum-backend"
main = "src/index.ts"
compatibility_date = "2024-04-19"
node_compat=true

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
